/**
 * BELGAUM TODAY - STATIC DATA
 * All countries, cities, themes, fonts, messages, and tips
 */

// ==================== 50+ COUNTRIES WITH 5-25 CITIES ====================
const WORLD_LOCATIONS = {
    "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", "Seattle", "Denver", "Washington DC", "Boston", "Detroit", "Nashville", "Portland", "Las Vegas"],
    "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Tianjin", "Wuhan", "Dongguan", "Chongqing", "Hangzhou", "Foshan", "Shenyang", "Xi'an", "Suzhou", "Harbin", "Zhengzhou", "Jinan", "Qingdao", "Nanjing", "Changsha"],
    "India": ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur", "Belgaum", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Mysore", "Goa"],
    "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Tangerang", "Depok", "Semarang", "Palembang", "Makassar", "South Tangerang", "Batam", "Bogor", "Pekanbaru", "Bandar Lampung"],
    "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Gujranwala", "Hyderabad", "Peshawar", "Islamabad", "Quetta", "Bahawalpur", "Sargodha"],
    "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Goiânia", "Belém", "Guarulhos", "Campinas", "São Luís"],
    "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Zaria", "Aba"],
    "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Rangpur", "Barisal", "Comilla", "Narayanganj", "Gazipur"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd"],
    "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Saltillo", "Mexicali", "Culiacán"],
    "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Saitama", "Hiroshima", "Sendai", "Chiba", "Kitakyushu", "Sakai"],
    "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar", "Hawassa", "Awasa", "Jimma", "Jijiga", "Shashamane"],
    "Philippines": ["Manila", "Quezon City", "Davao", "Caloocan", "Cebu City", "Zamboanga", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Dasmarinas", "Valenzuela", "Las Piñas", "Bacoor"],
    "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "El-Mahalla El-Kubra", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Aswan"],
    "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho", "Bien Hoa", "Vung Tau", "Nha Trang", "Hue", "Buon Ma Thuot", "Phan Thiet", "Cam Ranh", "Vinh", "My Tho", "Rach Gia"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin", "Eskişehir", "Diyarbakır", "Samsun", "Denizli", "Şanlıurfa"],
    "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Urmia", "Rasht", "Zahedan", "Kerman", "Hamadan", "Arak"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg"],
    "Thailand": ["Bangkok", "Samut Prakan", "Nonthaburi", "Udon Thani", "Chiang Mai", "Hat Yai", "Pak Kret", "Si Racha", "Phuket", "Khon Kaen", "Nakhon Ratchasima", "Surat Thani", "Ubon Ratchathani"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Newcastle", "Sheffield", "Bristol", "Edinburgh", "Leicester", "Nottingham", "Coventry", "Belfast", "Cardiff"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne", "Le Havre", "Toulon"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste"],
    "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Pietermaritzburg", "Benoni", "Tembisa", "East London", "Vereeniging", "Bloemfontein", "Boksburg", "Welkom", "Newcastle", "Krugersdorp"],
    "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang", "Yongin", "Seongnam", "Bucheon", "Cheongju", "Ansan"],
    "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Soledad", "Soacha", "Pasto", "Manizales", "Villavicencio"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón"],
    "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Santiago del Estero", "Corrientes"],
    "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice", "Białystok", "Gdynia", "Częstochowa", "Radom", "Sosnowiec"],
    "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Oshawa", "Windsor"],
    "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakesh", "Agadir", "Tangier", "Meknes", "Oujda", "Kenitra", "Tetouan"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Buraydah", "Khamis Mushait", "Hofuf", "Taif", "Najran", "Jizan", "Yanbu", "Abha"],
    "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo", "Chimbote", "Tacna", "Juliaca", "Ica", "Sullana", "Chincha Alta", "Huánuco"],
    "Malaysia": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City", "Kuching", "Kota Kinabalu", "Seremban", "Kajang", "Klang", "Subang Jaya", "Miri", "Kuala Terengganu"],
    "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Ashaiman", "Sunyani", "Cape Coast", "Obuasi", "Teshie", "Tema"],
    "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar", "Birgunj", "Dharan", "Butwal", "Hetauda", "Janakpur"],
    "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Puerto La Cruz", "Petare", "Turmero", "Ciudad Bolívar", "Mérida", "San Cristóbal", "Cabimas"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Newcastle", "Wollongong", "Logan City", "Geelong", "Hobart", "Townsville", "Cairns", "Darwin"],
    "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Banqiao", "Hsinchu", "Keelung", "Chiayi", "Changhua", "Taoyuan"],
    "Sri Lanka": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Negombo", "Kandy", "Kalmunai", "Galle", "Trincomalee", "Batticaloa", "Jaffna"],
    "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen"],
    "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst"],
    "Greece": ["Athens", "Thessaloniki", "Patras", "Piraeus", "Larissa", "Heraklion", "Peristeri", "Kallithea", "Acharnes", "Kalamaria"],
    "Portugal": ["Lisbon", "Porto", "Amadora", "Braga", "Setúbal", "Coimbra", "Queluz", "Funchal", "Cacém", "Vila Nova de Gaia"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"],
    "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn"],
    "Switzerland": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel"],
    "Israel": ["Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Holon", "Bnei Brak"],
    "UAE": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"],
    "Singapore": ["Singapore"],
    "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua"],
    "Norway": ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Frederiksberg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"]
};

// ==================== SEARCH TOPICS ====================
const SEARCH_TOPICS = ["Business", "Technology", "Entertainment", "Sports"];


// ==================== 10 WORKING FONTS (DIFFERENT STYLES) ====================
const FONTS = [
    { name: "Cormorant Garamond", family: "'Cormorant Garamond', serif" },
    { name: "Georgia", family: "'Georgia', serif" },
    { name: "Merriweather", family: "'Merriweather', serif" },
    { name: "Playfair Display", family: "'Playfair Display', serif" },
    { name: "Open Sans", family: "'Open Sans', sans-serif" },
    { name: "Raleway", family: "'Raleway', sans-serif" },
    { name: "PT Serif", family: "'PT Serif', serif" }
];


// ==================== 50 FUNNY LOADING MESSAGES ====================
const FUNNY_MESSAGES = [
    "Asking reporters to type faster... ⌨️",
    "Bribing the news servers with cookies 🍪",
    "Chasing down breaking stories 🏃",
    "Convincing headlines to load 📰",
    "Decoding journalist handwriting 📝",
    "Extracting news from the multiverse 🌌",
    "Feeding the news hamsters 🐹",
    "Gathering intel from pigeons 🕊️",
    "Herding news bytes like cats 🐱",
    "Interviewing the internet 🌐",
    "Juggling server requests 🤹",
    "Knocking on news doors 🚪",
    "Loading pixels one by one... 🎨",
    "Microwave-ing the headlines 📻",
    "Negotiating with cloud servers ☁️",
    "Organizing chaos into news 🌪️",
    "Polishing every word to perfection ✨",
    "Questioning the meaning of 'fast' 🤔",
    "Racing against time itself ⏱️",
    "Summoning the news spirits 👻",
    "Teaching robots to read 🤖",
    "Untangling network cables 🔌",
    "Verifying with unicorns 🦄",
    "Waiting for caffeine to kick in ☕",
    "X-raying the data packets 📡",
    "Yelling at lazy electrons ⚡",
    "Zipping through fiber optic cables 💨",
    "Asking nicely for news updates 🙏",
    "Battling server gremlins 👾",
    "Calculating the meaning of life: 42 🌟",
    "Debugging the universe 🐛",
    "Encrypting your patience 🔐",
    "Fishing for headlines in the cloud 🎣",
    "Googling 'how to load faster' 🔍",
    "Hiring faster hamsters 🐹💨",
    "Inspiring servers to work harder 💪",
    "Just a few more seconds... maybe 🤷",
    "Keeping the servers awake 😴",
    "Listening to server gossip 🗣️",
    "Making sure all pixels are happy 😊",
    "Negotiating with stubborn APIs 🤝",
    "Optimizing the flux capacitor ⚙️",
    "Persuading bytes to align properly 🧲",
    "Quantum entangling your request 🔬",
    "Rewinding the internet tapes 📼",
    "Shaking the magic 8-ball 🎱",
    "Training news ninjas 🥷",
    "Uploading good vibes only ✌️",
    "Validating the news matrix 📊",
    "Waking up sleeping servers 💤"
];

// ==================== TIPS ====================
const TIPS = [
    "💡 Did you know? News travels at the speed of light!",
    "🌍 Fun fact: We cover 50+ countries worldwide!",
    "⚡ Tip: Refresh for the latest updates!",
    "📱 Mobile-friendly design for news on the go!",
    "🎨 Try different themes in the header!",
    "🔤 Adjust font size with A+ and A- buttons!",
    "🌟 Advanced Search lets you search any country!",
    "🔍 Use Advanced Search for specific topics!",
    "📅 Historical news available by date!",
    "🚀 Lightning-fast news aggregation!"
];

console.log(`📦 Data loaded: ${Object.keys(WORLD_LOCATIONS).length} countries, ${FUNNY_MESSAGES.length} messages, ${TIPS.length} tips`);

// ==================== 50 FUNNY SEARCH MESSAGES ====================
const SEARCH_MESSAGES = [
    "🌍 Searching the globe for your news fix!",
    "🔍 Hunting down headlines from 50+ countries!",
    "📰 Your personal news detective is on the case!",
    "🌎 Scouring the planet for breaking stories!",
    "🗞️ Digging up news treasures worldwide!",
    "🌏 Your global news concierge at your service!",
    "📡 Beaming in news from every corner of Earth!",
    "🎯 Targeting the best stories just for you!",
    "🚀 Launching your news search into orbit!",
    "🌐 Connecting you to 500+ cities of news!",
    "🔭 Scanning the horizon for hot topics!",
    "📻 Tuning into global frequencies!",
    "🎪 Welcome to the greatest news show on Earth!",
    "🗺️ Mapping out your news journey!",
    "🧭 Navigating the news universe for you!",
    "🎬 Lights, camera, news action!",
    "🎭 The world is your news stage!",
    "🎨 Painting your news canvas globally!",
    "🎵 Orchestrating a symphony of headlines!",
    "🎪 Step right up to the news carnival!",
    "🌟 Wish upon a news star!",
    "🎁 Unwrapping news gifts from around the world!",
    "🎯 Bulls-eye! Finding your perfect story!",
    "🎲 Rolling the dice on global news!",
    "🎰 Hitting the news jackpot!",
    "🎪 The circus of worldwide news!",
    "🎢 Riding the news roller coaster!",
    "🎡 Taking a spin on the news wheel!",
    "🎠 Hop on the news merry-go-round!",
    "🎪 Three rings of global coverage!",
    "🌈 Following the news rainbow!",
    "⚡ Lightning-fast global news delivery!",
    "🔥 Heating up with hot news from everywhere!",
    "❄️ Cool stories from the coolest places!",
    "🌊 Surfing the waves of world news!",
    "🏔️ Climbing mountains of information!",
    "🏖️ Beach-combing for news pearls!",
    "🏜️ No desert of news here!",
    "🌲 Growing a forest of fresh stories!",
    "🌺 Blooming with beautiful news!",
    "🍀 Lucky you! News from everywhere!",
    "🌸 Spring into action with global news!",
    "🍂 Fall in love with worldwide stories!",
    "❄️ Winter wonderland of news!",
    "☀️ Sunny side up news from the globe!",
    "🌙 Moonlight serenade of headlines!",
    "⭐ Star-studded news lineup!",
    "💫 Cosmic coverage from planet Earth!",
    "🌠 Shooting star stories incoming!",
    "🪐 Out of this world news search!"
];

console.log(`📦 Data loaded: ${Object.keys(WORLD_LOCATIONS).length} countries, ${FUNNY_MESSAGES.length} messages, ${TIPS.length} tips, ${SEARCH_MESSAGES.length} search messages`);
